### ISSUE TITLE
speller skill fails install

### ISSUE THREAD

**Issue by hipitihop** [project-alice-powered-by-snips/ProjectAliceModules#109]
```
2020-03-02 18:54:52,488 [Thread-3641] - [ERROR] - [SkillManager] Couldn't instantiate skill Speller.Speller: 'icon'
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 216, in importFromSkill
    instance: AliceSkill = klass()
  File "/home/pi/ProjectAlice/core/base/model/AliceSkill.py", line 39, in __init__
    self._icon = self._install['icon']
KeyError: 'icon'

```

**Comment by Psychokiller1888** [comment]
That would mean you are on alpha 6 and the skill is on master because the icon is defined for the skill:
https://github.com/project-alice-assistant/skill_Speller/blob/master/Speller.install

**Comment by hipitihop** [comment]
speller now working, thanks
