### ISSUE TITLE
[BUG] FreeCurrencyConverter: converting not working

### ISSUE THREAD

**Issue by Fe3lApAcUt** [project-alice-powered-by-snips/ProjectAliceModules#119]
**Describe the bug**
Converting from "Schweizer Franken" nach "Euro" not working

**To Reproduce**
Ask Alice to convert currency

**Expected behavior**
Alice should convert the currency

**Logs**
```
2020-04-04 20:27:49,543 [Thread-1] - [ERROR] - [SkillManager]            Error dispatching message to FreeCurrencyConverterDotCom: init() got an unexpected keyword argument 'depth'
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/util/Decorators.py", line 147, in exceptionDecorator
    return func(*args, **kwargs)
  File "/home/pi/ProjectAlice/core/util/Decorators.py", line 127, in offlineDecorator
    return func(*args, **kwargs)
  File "/home/pi/ProjectAlice/skills/FreeCurrencyConverterDotCom/FreeCurrencyConverterDotCom.py", line 56, in convertCurrencyIntent
    conversion = data[f'{fromCurrency}_{toCurrency}']
KeyError: 'Schweizer Franken_Euro'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 278, in dispatchMessage
    consumed = skillInstance.onMessageDispatch(session)
  File "/home/pi/ProjectAlice/core/base/model/AliceSkill.py", line 425, in onMessageDispatch
    ret = function(session=session)
  File "/home/pi/ProjectAlice/core/util/Decorators.py", line 149, in exceptionDecorator
    Logger(depth=6).logWarning(msg=e, printStack=printStack)
TypeError: __init__() got an unexpected keyword argument 'depth'
```

**Alice version**
1.0.0-b1

**Comment by philipp2310** [comment]
2 problems:
1. it should not try to read for "Schweizer Franken_Euro", that has to be "CHF_EUR" - the training would in theory translate that way, no Idea why it is not doing so at the moment
-> testing takes time... too many skills in my Alice ;)

2. there is currently no error when the requested currency doesn't exist in their database
-> locally fixed

**Comment by philipp2310** [comment]
1. -> using session.slots.get() but session.slots only contains RAW input - that is good for voice output, but for the technical case the session.slotValue() method has to be used!

**Comment by philipp2310** [comment]
please retest and close if successful! thanks!
