### ISSUE TITLE
[BUG] SpeedTest fails on RC3

### ISSUE THREAD

**Issue by hipitihop** [project-alice-powered-by-snips/ProjectAliceModules#140]
**Describe the bug**
Running SpeedTest fails silently. She acknweldges that she will return in a while but never does.

**To Reproduce**
Ask her to run a speed test.

**Expected behavior**
Run the speed test and report results, or report that something went wrong and to check the logs.

**Logs**
Get your logs at ~/ProjectAlice/var/logs

```
2021-06-09T07:14:42.260285780Z [Speedtest]               Starting Speedtest
2021-06-09T07:14:42.260725302Z [SkillManager]            The intent "Speedtest" was consumed by Speedtest
2021-06-09T07:14:42.270289498Z [AmazonTts]               Using existing cached file 701e58f0cdc9a55d7a38d703de62ab47
2021-06-09T07:15:00.511096746Z Exception in thread Thread-358794:
2021-06-09T07:15:00.511129057Z Traceback (most recent call last):
2021-06-09T07:15:00.511134457Z   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
2021-06-09T07:15:00.511150568Z     self.run()
2021-06-09T07:15:00.511154255Z   File "/usr/local/lib/python3.7/threading.py", line 1177, in run
2021-06-09T07:15:00.511157681Z     self.function(*self.args, **self.kwargs)
2021-06-09T07:15:00.511161148Z   File "/home/pi/ProjectAlice/core/util/ThreadManager.py", line 113, in onTimerEnd
2021-06-09T07:15:00.511164785Z     timer.callback(*timer.args, **timer.kwargs)
2021-06-09T07:15:00.511168041Z   File "/home/pi/ProjectAlice/core/util/Decorators.py", line 171, in exceptionDecorator
2021-06-09T07:15:00.511171447Z     return func(*args, **kwargs)
2021-06-09T07:15:00.511174814Z   File "/home/pi/ProjectAlice/core/util/Decorators.py", line 150, in offlineDecorator
2021-06-09T07:15:00.511178901Z     return func(*args, **kwargs)
2021-06-09T07:15:00.511182107Z   File "/home/pi/ProjectAlice/skills/Speedtest/Speedtest.py", line 26, in executeSpeedtest
2021-06-09T07:15:00.511185454Z     speed = speedtest.Speedtest()
2021-06-09T07:15:00.511188610Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/speedtest.py", line 1091, in __init__
2021-06-09T07:15:00.511192116Z     self.get_config()
2021-06-09T07:15:00.511195252Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/speedtest.py", line 1174, in get_config
2021-06-09T07:15:00.511198609Z     map(int, server_config['ignoreids'].split(','))
2021-06-09T07:15:00.511201835Z ValueError: invalid literal for int() with base 10: ''
```

**Alice version**
1.0.0-RC1

**Additional context**
Worked at some point but I don't remember trying on main docker and I have not done a git bisect.

**Comment by hipitihop** [comment]
Still occurring on RC5

```
2021-06-27T02:10:35.255994949Z [Speedtest]               Starting Speedtest
2021-06-27T02:10:35.256292442Z [SkillManager]            The intent "Speedtest" was consumed by Speedtest
2021-06-27T02:10:35.298826537Z [AmazonTts]               Using existing cached file 701e58f0cdc9a55d7a38d703de62ab47
2021-06-27T02:10:51.242218908Z Exception in thread Thread-85342:
2021-06-27T02:10:51.242255427Z Traceback (most recent call last):
2021-06-27T02:10:51.242261689Z   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
2021-06-27T02:10:51.242268371Z     self.run()
2021-06-27T02:10:51.242274042Z   File "/usr/local/lib/python3.7/threading.py", line 1177, in run
2021-06-27T02:10:51.242279462Z     self.function(*self.args, **self.kwargs)
2021-06-27T02:10:51.242283189Z   File "/home/pi/ProjectAlice/core/util/ThreadManager.py", line 113, in onTimerEnd
2021-06-27T02:10:51.242287177Z     timer.callback(*timer.args, **timer.kwargs)
2021-06-27T02:10:51.242290884Z   File "/home/pi/ProjectAlice/core/util/Decorators.py", line 171, in exceptionDecorator
2021-06-27T02:10:51.242294711Z     return func(*args, **kwargs)
2021-06-27T02:10:51.242298528Z   File "/home/pi/ProjectAlice/core/util/Decorators.py", line 150, in offlineDecorator
2021-06-27T02:10:51.242304249Z     return func(*args, **kwargs)
2021-06-27T02:10:51.242307916Z   File "/home/pi/ProjectAlice/skills/Speedtest/Speedtest.py", line 26, in executeSpeedtest
2021-06-27T02:10:51.242311713Z     speed = speedtest.Speedtest()
2021-06-27T02:10:51.242315290Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/speedtest.py", line 1091, in __init__
2021-06-27T02:10:51.242319168Z     self.get_config()
2021-06-27T02:10:51.242322875Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/speedtest.py", line 1174, in get_config
2021-06-27T02:10:51.242326612Z     map(int, server_config['ignoreids'].split(','))
2021-06-27T02:10:51.242330269Z ValueError: invalid literal for int() with base 10: ''
```
